language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.1

    # The SDK version used to compile your project
    - android-25

    # Additional components
    #not needed now: - extra-google-m2repository
    - extra-android-m2repository

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - ./gradlew build jacocoTestReport